{
  "project_id_env": "CROWDIN_PROJECT_ID",
  "api_token_env": "CROWDIN_PERSONAL_TOKEN",
  "base_path": "./",
  "preserve_hierarchy": true,
  "base_url": "https://api.crowdin.com",
  "files": [
    {
      "source": "/src/Mcc.Cli/Localization/Resources/MccStrings.resx",
      "translation": "/src/Mcc.Cli/Localization/Resources/MccStrings.%locale%.resx"
    },
    {
      "source": "/src/Mcc.Cli/Resources/TextResources.resx",
      "translation": "/src/Mcc.Cli/Resources/TextResources.%locale%.resx"
    },
    {
      "source": "/src/Mcc.Cli/Localization/Resources/ContainerArt.resx",
      "translation": "/src/Mcc.Cli/Localization/Resources/ContainerArt.%locale%.resx"
    },
    {
      "source": "/docs/**/*.md",
      "translation": "/docs/l10n/%locale%/**/%original_file_name%",
      "ignore": [
        "/docs/l10n/**",
        "/docs/.vuepress/**",
        "/docs/node_modules/**"
      ]
    },
    {
      "source": "/docs/.vuepress/ui/en.json",
      "translation": "/docs/.vuepress/ui/%locale%.json"
    }
  ]
}
