files:
  - source: /MinecraftClient/Resources/Translations/Translations.resx
    translation: /MinecraftClient/Resources/Translations/Translations.%osx_code%.resx
  - source: /MinecraftClient/Resources/AsciiArt/AsciiArt.resx
    translation: /MinecraftClient/Resources/AsciiArt/AsciiArt.%osx_code%.resx
  - source: /README.md
    translation: /README/README-%language%.md
