using System.Collections.Generic;

namespace MinecraftClient.Mapping.EntityPalettes
{
    public class EntityPalette1216 : EntityPalette
    {
        private static readonly Dictionary<int, EntityType> mappings = new();

        static EntityPalette1216()
        {
            mappings[0] = EntityType.AcaciaBoat;
            mappings[1] = EntityType.AcaciaChestBoat;
            mappings[2] = EntityType.Allay;
            mappings[3] = EntityType.AreaEffectCloud;
            mappings[4] = EntityType.Armadillo;
            mappings[5] = EntityType.ArmorStand;
            mappings[6] = EntityType.Arrow;
            mappings[7] = EntityType.Axolotl;
            mappings[8] = EntityType.BambooChestRaft;
            mappings[9] = EntityType.BambooRaft;
            mappings[10] = EntityType.Bat;
            mappings[11] = EntityType.Bee;
            mappings[12] = EntityType.BirchBoat;
            mappings[13] = EntityType.BirchChestBoat;
            mappings[14] = EntityType.Blaze;
            mappings[15] = EntityType.BlockDisplay;
            mappings[16] = EntityType.Bogged;
            mappings[17] = EntityType.Breeze;
            mappings[18] = EntityType.BreezeWindCharge;
            mappings[19] = EntityType.Camel;
            mappings[20] = EntityType.Cat;
            mappings[21] = EntityType.CaveSpider;
            mappings[22] = EntityType.CherryBoat;
            mappings[23] = EntityType.CherryChestBoat;
            mappings[24] = EntityType.ChestMinecart;
            mappings[25] = EntityType.Chicken;
            mappings[26] = EntityType.Cod;
            mappings[27] = EntityType.CommandBlockMinecart;
            mappings[28] = EntityType.Cow;
            mappings[29] = EntityType.Creaking;
            mappings[30] = EntityType.Creeper;
            mappings[31] = EntityType.DarkOakBoat;
            mappings[32] = EntityType.DarkOakChestBoat;
            mappings[33] = EntityType.Dolphin;
            mappings[34] = EntityType.Donkey;
            mappings[35] = EntityType.DragonFireball;
            mappings[36] = EntityType.Drowned;
            mappings[37] = EntityType.Egg;
            mappings[38] = EntityType.ElderGuardian;
            mappings[39] = EntityType.Enderman;
            mappings[40] = EntityType.Endermite;
            mappings[41] = EntityType.EnderDragon;
            mappings[42] = EntityType.EnderPearl;
            mappings[43] = EntityType.EndCrystal;
            mappings[44] = EntityType.Evoker;
            mappings[45] = EntityType.EvokerFangs;
            mappings[46] = EntityType.ExperienceBottle;
            mappings[47] = EntityType.ExperienceOrb;
            mappings[48] = EntityType.EyeOfEnder;
            mappings[49] = EntityType.FallingBlock;
            mappings[50] = EntityType.Fireball;
            mappings[51] = EntityType.FireworkRocket;
            mappings[52] = EntityType.Fox;
            mappings[53] = EntityType.Frog;
            mappings[54] = EntityType.FurnaceMinecart;
            mappings[55] = EntityType.Ghast;
            mappings[56] = EntityType.HappyGhast;
            mappings[57] = EntityType.Giant;
            mappings[58] = EntityType.GlowItemFrame;
            mappings[59] = EntityType.GlowSquid;
            mappings[60] = EntityType.Goat;
            mappings[61] = EntityType.Guardian;
            mappings[62] = EntityType.Hoglin;
            mappings[63] = EntityType.HopperMinecart;
            mappings[64] = EntityType.Horse;
            mappings[65] = EntityType.Husk;
            mappings[66] = EntityType.Illusioner;
            mappings[67] = EntityType.Interaction;
            mappings[68] = EntityType.IronGolem;
            mappings[69] = EntityType.Item;
            mappings[70] = EntityType.ItemDisplay;
            mappings[71] = EntityType.ItemFrame;
            mappings[72] = EntityType.JungleBoat;
            mappings[73] = EntityType.JungleChestBoat;
            mappings[74] = EntityType.LeashKnot;
            mappings[75] = EntityType.LightningBolt;
            mappings[76] = EntityType.Llama;
            mappings[77] = EntityType.LlamaSpit;
            mappings[78] = EntityType.MagmaCube;
            mappings[79] = EntityType.MangroveBoat;
            mappings[80] = EntityType.MangroveChestBoat;
            mappings[81] = EntityType.Marker;
            mappings[82] = EntityType.Minecart;
            mappings[83] = EntityType.Mooshroom;
            mappings[84] = EntityType.Mule;
            mappings[85] = EntityType.OakBoat;
            mappings[86] = EntityType.OakChestBoat;
            mappings[87] = EntityType.Ocelot;
            mappings[88] = EntityType.OminousItemSpawner;
            mappings[89] = EntityType.Painting;
            mappings[90] = EntityType.PaleOakBoat;
            mappings[91] = EntityType.PaleOakChestBoat;
            mappings[92] = EntityType.Panda;
            mappings[93] = EntityType.Parrot;
            mappings[94] = EntityType.Phantom;
            mappings[95] = EntityType.Pig;
            mappings[96] = EntityType.Piglin;
            mappings[97] = EntityType.PiglinBrute;
            mappings[98] = EntityType.Pillager;
            mappings[99] = EntityType.PolarBear;
            mappings[100] = EntityType.SplashPotion;
            mappings[101] = EntityType.LingeringPotion;
            mappings[102] = EntityType.Pufferfish;
            mappings[103] = EntityType.Rabbit;
            mappings[104] = EntityType.Ravager;
            mappings[105] = EntityType.Salmon;
            mappings[106] = EntityType.Sheep;
            mappings[107] = EntityType.Shulker;
            mappings[108] = EntityType.ShulkerBullet;
            mappings[109] = EntityType.Silverfish;
            mappings[110] = EntityType.Skeleton;
            mappings[111] = EntityType.SkeletonHorse;
            mappings[112] = EntityType.Slime;
            mappings[113] = EntityType.SmallFireball;
            mappings[114] = EntityType.Sniffer;
            mappings[115] = EntityType.Snowball;
            mappings[116] = EntityType.SnowGolem;
            mappings[117] = EntityType.SpawnerMinecart;
            mappings[118] = EntityType.SpectralArrow;
            mappings[119] = EntityType.Spider;
            mappings[120] = EntityType.SpruceBoat;
            mappings[121] = EntityType.SpruceChestBoat;
            mappings[122] = EntityType.Squid;
            mappings[123] = EntityType.Stray;
            mappings[124] = EntityType.Strider;
            mappings[125] = EntityType.Tadpole;
            mappings[126] = EntityType.TextDisplay;
            mappings[127] = EntityType.Tnt;
            mappings[128] = EntityType.TntMinecart;
            mappings[129] = EntityType.TraderLlama;
            mappings[130] = EntityType.Trident;
            mappings[131] = EntityType.TropicalFish;
            mappings[132] = EntityType.Turtle;
            mappings[133] = EntityType.Vex;
            mappings[134] = EntityType.Villager;
            mappings[135] = EntityType.Vindicator;
            mappings[136] = EntityType.WanderingTrader;
            mappings[137] = EntityType.Warden;
            mappings[138] = EntityType.WindCharge;
            mappings[139] = EntityType.Witch;
            mappings[140] = EntityType.Wither;
            mappings[141] = EntityType.WitherSkeleton;
            mappings[142] = EntityType.WitherSkull;
            mappings[143] = EntityType.Wolf;
            mappings[144] = EntityType.Zoglin;
            mappings[145] = EntityType.Zombie;
            mappings[146] = EntityType.ZombieHorse;
            mappings[147] = EntityType.ZombieVillager;
            mappings[148] = EntityType.ZombifiedPiglin;
            mappings[149] = EntityType.Player;
            mappings[150] = EntityType.FishingBobber;
        }

        protected override Dictionary<int, EntityType> GetDict()
        {
            return mappings;
        }
    }
}
