//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftClient {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigComments {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigComments() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MinecraftClient.Resources.ConfigComments.ConfigComments", typeof(ConfigComments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppVars_Variables {
            get {
                return ResourceManager.GetString("AppVars.Variables", resourceCulture);
            }
        }
        
        internal static string ChatBot {
            get {
                return ResourceManager.GetString("ChatBot", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts {
            get {
                return ResourceManager.GetString("ChatBot.Alerts", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Beep_Enabled {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Beep_Enabled", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Excludes {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Excludes", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Log_File {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Log_File", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Log_To_File {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Log_To_File", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Matches {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Matches", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Trigger_By_Rain {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Trigger_By_Rain", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Trigger_By_Thunderstorm {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Trigger_By_Thunderstorm", resourceCulture);
            }
        }
        
        internal static string ChatBot_Alerts_Trigger_By_Words {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Trigger_By_Words", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk_Command {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Command", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Delay", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk_Use_Sneak {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Use_Sneak", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk_Use_Terrain_Handling {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Use_Terrain_Handling", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk_Walk_Range {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Walk_Range", resourceCulture);
            }
        }
        
        internal static string ChatBot_AntiAfk_Walk_Retries {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Walk_Retries", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Attack_Hostile {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Attack_Hostile", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Attack_Passive {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Attack_Passive", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Attack_Range {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Attack_Range", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Cooldown_Time {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Cooldown_Time", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Entites_List {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Entites_List", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Interaction {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Interaction", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_List_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.List_Mode", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Mode", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoAttack_Priority {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Priority", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoCraft {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoCraft_CraftingTable {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft.CraftingTable", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoCraft_OnFailure {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft.OnFailure", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoCraft_Recipes {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft.Recipes", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Auto_Start_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Auto_Start_Delay", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Auto_Tool_Switch {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Auto_Tool_Switch", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Dig_Timeout {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Dig_Timeout", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Drop_Low_Durability_Tools {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Drop_Low_Durability_Tools", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Durability_Limit {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Durability_Limit", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_List_Type {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.List_Type", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Locations {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Locations", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Location_Order {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Location_Order", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Log_Block_Dig {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Log_Block_Dig", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDig_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Mode", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDrop {
            get {
                return ResourceManager.GetString("ChatBot.AutoDrop", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoDrop_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoDrop.Mode", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoEat {
            get {
                return ResourceManager.GetString("ChatBot.AutoEat", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Antidespawn {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Antidespawn", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Auto_Rod_Switch {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Auto_Rod_Switch", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Auto_Start {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Auto_Start", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Cast_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Cast_Delay", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Durability_Limit {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Durability_Limit", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Enable_Move {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Enable_Move", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Fishing_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Fishing_Delay", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Fishing_Timeout {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Fishing_Timeout", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Hook_Threshold {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Hook_Threshold", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Log_Fish_Bobber {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Log_Fish_Bobber", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Mainhand {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Mainhand", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Movements {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Movements", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoFishing_Stationary_Threshold {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Stationary_Threshold", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRelog {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRelog_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Delay", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRelog_Ignore_Kick_Message {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Ignore_Kick_Message", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRelog_Kick_Messages {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Kick_Messages", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRelog_Retries {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Retries", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRespond {
            get {
                return ResourceManager.GetString("ChatBot.AutoRespond", resourceCulture);
            }
        }
        
        internal static string ChatBot_AutoRespond_Match_Colors {
            get {
                return ResourceManager.GetString("ChatBot.AutoRespond.Match_Colors", resourceCulture);
            }
        }
        
        internal static string ChatBot_ChatLog {
            get {
                return ResourceManager.GetString("ChatBot.ChatLog", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge_ChannelId {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.ChannelId", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge_Formats {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.Formats", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge_GuildId {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.GuildId", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge_MessageSendTimeout {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.MessageSendTimeout", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge_OwnersIds {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.OwnersIds", resourceCulture);
            }
        }
        
        internal static string ChatBot_DiscordBridge_Token {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.Token", resourceCulture);
            }
        }
        
        internal static string ChatBot_Farmer {
            get {
                return ResourceManager.GetString("ChatBot.Farmer", resourceCulture);
            }
        }
        
        internal static string ChatBot_Farmer_Delay_Between_Tasks {
            get {
                return ResourceManager.GetString("ChatBot.Farmer.Delay_Between_Tasks", resourceCulture);
            }
        }
        
        internal static string ChatBot_FollowPlayer {
            get {
                return ResourceManager.GetString("ChatBot.FollowPlayer", resourceCulture);
            }
        }
        
        internal static string ChatBot_FollowPlayer_Stop_At_Distance {
            get {
                return ResourceManager.GetString("ChatBot.FollowPlayer.Stop_At_Distance", resourceCulture);
            }
        }
        
        internal static string ChatBot_FollowPlayer_Update_Limit {
            get {
                return ResourceManager.GetString("ChatBot.FollowPlayer.Update_Limit", resourceCulture);
            }
        }
        
        internal static string ChatBot_HangmanGame {
            get {
                return ResourceManager.GetString("ChatBot.HangmanGame", resourceCulture);
            }
        }
        
        internal static string ChatBot_Mailer {
            get {
                return ResourceManager.GetString("ChatBot.Mailer", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map {
            get {
                return ResourceManager.GetString("ChatBot.Map", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Auto_Render_On_Update {
            get {
                return ResourceManager.GetString("ChatBot.Map.Auto_Render_On_Update", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Delete_All_On_Unload {
            get {
                return ResourceManager.GetString("ChatBot.Map.Delete_All_On_Unload", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Notify_On_First_Update {
            get {
                return ResourceManager.GetString("ChatBot.Map.Notify_On_First_Update", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Rasize_Rendered_Image {
            get {
                return ResourceManager.GetString("ChatBot.Map.Rasize_Rendered_Image", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Render_In_Console {
            get {
                return ResourceManager.GetString("ChatBot.Map.Render_In_Console", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Resize_To {
            get {
                return ResourceManager.GetString("ChatBot.Map.Resize_To", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Save_To_File {
            get {
                return ResourceManager.GetString("ChatBot.Map.Save_To_File", resourceCulture);
            }
        }
        
        internal static string ChatBot_Map_Send_Rendered_To_Bridges {
            get {
                return ResourceManager.GetString("ChatBot.Map.Send_Rendered_To_Bridges", resourceCulture);
            }
        }
        
        internal static string ChatBot_PlayerListLogger {
            get {
                return ResourceManager.GetString("ChatBot.PlayerListLogger", resourceCulture);
            }
        }
        
        internal static string ChatBot_PlayerListLogger_Delay {
            get {
                return ResourceManager.GetString("ChatBot.PlayerListLogger.Delay", resourceCulture);
            }
        }
        
        internal static string ChatBot_RemoteControl {
            get {
                return ResourceManager.GetString("ChatBot.RemoteControl", resourceCulture);
            }
        }
        
        internal static string ChatBot_ReplayCapture {
            get {
                return ResourceManager.GetString("ChatBot.ReplayCapture", resourceCulture);
            }
        }
        
        internal static string ChatBot_ReplayCapture_Backup_Interval {
            get {
                return ResourceManager.GetString("ChatBot.ReplayCapture.Backup_Interval", resourceCulture);
            }
        }
        
        internal static string ChatBot_ScriptScheduler {
            get {
                return ResourceManager.GetString("ChatBot.ScriptScheduler", resourceCulture);
            }
        }
        
        internal static string ChatBot_TelegramBridge {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge", resourceCulture);
            }
        }
        
        internal static string ChatBot_TelegramBridge_Authorized_Chat_Ids {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.Authorized_Chat_Ids", resourceCulture);
            }
        }
        
        internal static string ChatBot_TelegramBridge_ChannelId {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.ChannelId", resourceCulture);
            }
        }
        
        internal static string ChatBot_TelegramBridge_Formats {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.Formats", resourceCulture);
            }
        }
        
        internal static string ChatBot_TelegramBridge_MessageSendTimeout {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.MessageSendTimeout", resourceCulture);
            }
        }
        
        internal static string ChatBot_TelegramBridge_Token {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.Token", resourceCulture);
            }
        }
        
        internal static string ChatFormat {
            get {
                return ResourceManager.GetString("ChatFormat", resourceCulture);
            }
        }
        
        internal static string ChatFormat_Builtins {
            get {
                return ResourceManager.GetString("ChatFormat.Builtins", resourceCulture);
            }
        }
        
        internal static string ChatFormat_UserDefined {
            get {
                return ResourceManager.GetString("ChatFormat.UserDefined", resourceCulture);
            }
        }
        
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        internal static string Console_CommandSuggestion {
            get {
                return ResourceManager.GetString("Console.CommandSuggestion", resourceCulture);
            }
        }
        
        internal static string Console_CommandSuggestion_Enable {
            get {
                return ResourceManager.GetString("Console.CommandSuggestion.Enable", resourceCulture);
            }
        }
        
        internal static string Console_CommandSuggestion_Use_Basic_Arrow {
            get {
                return ResourceManager.GetString("Console.CommandSuggestion.Use_Basic_Arrow", resourceCulture);
            }
        }
        
        internal static string Console_General_ConsoleColorMode {
            get {
                return ResourceManager.GetString("Console.General.ConsoleColorMode", resourceCulture);
            }
        }
        
        internal static string Console_General_Display_Input {
            get {
                return ResourceManager.GetString("Console.General.Display_Input", resourceCulture);
            }
        }
        
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        internal static string Logging_ChatFilter {
            get {
                return ResourceManager.GetString("Logging.ChatFilter", resourceCulture);
            }
        }
        
        internal static string Logging_ChatMessages {
            get {
                return ResourceManager.GetString("Logging.ChatMessages", resourceCulture);
            }
        }
        
        internal static string Logging_DebugFilter {
            get {
                return ResourceManager.GetString("Logging.DebugFilter", resourceCulture);
            }
        }
        
        internal static string Logging_DebugMessages {
            get {
                return ResourceManager.GetString("Logging.DebugMessages", resourceCulture);
            }
        }
        
        internal static string Logging_ErrorMessages {
            get {
                return ResourceManager.GetString("Logging.ErrorMessages", resourceCulture);
            }
        }
        
        internal static string Logging_FilterMode {
            get {
                return ResourceManager.GetString("Logging.FilterMode", resourceCulture);
            }
        }
        
        internal static string Logging_InfoMessages {
            get {
                return ResourceManager.GetString("Logging.InfoMessages", resourceCulture);
            }
        }
        
        internal static string Logging_LogFile {
            get {
                return ResourceManager.GetString("Logging.LogFile", resourceCulture);
            }
        }
        
        internal static string Logging_LogToFile {
            get {
                return ResourceManager.GetString("Logging.LogToFile", resourceCulture);
            }
        }
        
        internal static string Logging_PrependTimestamp {
            get {
                return ResourceManager.GetString("Logging.PrependTimestamp", resourceCulture);
            }
        }
        
        internal static string Logging_SaveColorCodes {
            get {
                return ResourceManager.GetString("Logging.SaveColorCodes", resourceCulture);
            }
        }
        
        internal static string Logging_WarningMessages {
            get {
                return ResourceManager.GetString("Logging.WarningMessages", resourceCulture);
            }
        }
        
        internal static string Main_Advanced {
            get {
                return ResourceManager.GetString("Main.Advanced", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_account_list {
            get {
                return ResourceManager.GetString("Main.Advanced.account_list", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_auto_respawn {
            get {
                return ResourceManager.GetString("Main.Advanced.auto_respawn", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_bot_owners {
            get {
                return ResourceManager.GetString("Main.Advanced.bot_owners", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_brand_info {
            get {
                return ResourceManager.GetString("Main.Advanced.brand_info", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_chatbot_log_file {
            get {
                return ResourceManager.GetString("Main.Advanced.chatbot_log_file", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_enable_emoji {
            get {
                return ResourceManager.GetString("Main.Advanced.enable_emoji", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_entity_handling {
            get {
                return ResourceManager.GetString("Main.Advanced.entity_handling", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_exit_on_failure {
            get {
                return ResourceManager.GetString("Main.Advanced.exit_on_failure", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_internal_cmd_char {
            get {
                return ResourceManager.GetString("Main.Advanced.internal_cmd_char", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_inventory_handling {
            get {
                return ResourceManager.GetString("Main.Advanced.inventory_handling", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_language {
            get {
                return ResourceManager.GetString("Main.Advanced.language", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_LoadMccTrans {
            get {
                return ResourceManager.GetString("Main.Advanced.LoadMccTrans", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_mc_forge {
            get {
                return ResourceManager.GetString("Main.Advanced.mc_forge", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_mc_version {
            get {
                return ResourceManager.GetString("Main.Advanced.mc_version", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_message_cooldown {
            get {
                return ResourceManager.GetString("Main.Advanced.message_cooldown", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_minecraft_realms {
            get {
                return ResourceManager.GetString("Main.Advanced.minecraft_realms", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_MinTerminalHeight {
            get {
                return ResourceManager.GetString("Main.Advanced.MinTerminalHeight", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_MinTerminalWidth {
            get {
                return ResourceManager.GetString("Main.Advanced.MinTerminalWidth", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_movement_speed {
            get {
                return ResourceManager.GetString("Main.Advanced.movement_speed", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_move_head_while_walking {
            get {
                return ResourceManager.GetString("Main.Advanced.move_head_while_walking", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_player_head_icon {
            get {
                return ResourceManager.GetString("Main.Advanced.player_head_icon", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_private_msgs_cmd_name {
            get {
                return ResourceManager.GetString("Main.Advanced.private_msgs_cmd_name", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_profilekey_cache {
            get {
                return ResourceManager.GetString("Main.Advanced.profilekey_cache", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_resolve_srv_records {
            get {
                return ResourceManager.GetString("Main.Advanced.resolve_srv_records", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_script_cache {
            get {
                return ResourceManager.GetString("Main.Advanced.script_cache", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_server_list {
            get {
                return ResourceManager.GetString("Main.Advanced.server_list", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_session_cache {
            get {
                return ResourceManager.GetString("Main.Advanced.session_cache", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_show_chat_links {
            get {
                return ResourceManager.GetString("Main.Advanced.show_chat_links", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_show_inventory_layout {
            get {
                return ResourceManager.GetString("Main.Advanced.show_inventory_layout", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_show_system_messages {
            get {
                return ResourceManager.GetString("Main.Advanced.show_system_messages", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_show_xpbar_messages {
            get {
                return ResourceManager.GetString("Main.Advanced.show_xpbar_messages", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_temporary_fix_badpacket {
            get {
                return ResourceManager.GetString("Main.Advanced.temporary_fix_badpacket", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_terrain_and_movements {
            get {
                return ResourceManager.GetString("Main.Advanced.terrain_and_movements", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_timeout {
            get {
                return ResourceManager.GetString("Main.Advanced.timeout", resourceCulture);
            }
        }
        
        internal static string Main_Advanced_timestamps {
            get {
                return ResourceManager.GetString("Main.Advanced.timestamps", resourceCulture);
            }
        }
        
        internal static string Main_General_account {
            get {
                return ResourceManager.GetString("Main.General.account", resourceCulture);
            }
        }
        
        internal static string Main_General_login {
            get {
                return ResourceManager.GetString("Main.General.login", resourceCulture);
            }
        }
        
        internal static string Main_General_method {
            get {
                return ResourceManager.GetString("Main.General.method", resourceCulture);
            }
        }
        
        internal static string Main_General_server_info {
            get {
                return ResourceManager.GetString("Main.General.server_info", resourceCulture);
            }
        }
        
        internal static string MCSettings {
            get {
                return ResourceManager.GetString("MCSettings", resourceCulture);
            }
        }
        
        internal static string MCSettings_ChatColors {
            get {
                return ResourceManager.GetString("MCSettings.ChatColors", resourceCulture);
            }
        }
        
        internal static string MCSettings_ChatMode {
            get {
                return ResourceManager.GetString("MCSettings.ChatMode", resourceCulture);
            }
        }
        
        internal static string MCSettings_Difficulty {
            get {
                return ResourceManager.GetString("MCSettings.Difficulty", resourceCulture);
            }
        }
        
        internal static string MCSettings_Enabled {
            get {
                return ResourceManager.GetString("MCSettings.Enabled", resourceCulture);
            }
        }
        
        internal static string MCSettings_Locale {
            get {
                return ResourceManager.GetString("MCSettings.Locale", resourceCulture);
            }
        }
        
        internal static string MCSettings_MainHand {
            get {
                return ResourceManager.GetString("MCSettings.MainHand", resourceCulture);
            }
        }
        
        internal static string MCSettings_RenderDistance {
            get {
                return ResourceManager.GetString("MCSettings.RenderDistance", resourceCulture);
            }
        }
        
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        internal static string Proxy_Enabled_Ingame {
            get {
                return ResourceManager.GetString("Proxy.Enabled_Ingame", resourceCulture);
            }
        }
        
        internal static string Proxy_Enabled_Login {
            get {
                return ResourceManager.GetString("Proxy.Enabled_Login", resourceCulture);
            }
        }
        
        internal static string Proxy_Enabled_Update {
            get {
                return ResourceManager.GetString("Proxy.Enabled_Update", resourceCulture);
            }
        }
        
        internal static string Proxy_Password {
            get {
                return ResourceManager.GetString("Proxy.Password", resourceCulture);
            }
        }
        
        internal static string Proxy_Proxy_Type {
            get {
                return ResourceManager.GetString("Proxy.Proxy_Type", resourceCulture);
            }
        }
        
        internal static string Proxy_Server {
            get {
                return ResourceManager.GetString("Proxy.Server", resourceCulture);
            }
        }
        
        internal static string Proxy_Username {
            get {
                return ResourceManager.GetString("Proxy.Username", resourceCulture);
            }
        }
        
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        internal static string Signature_LoginWithSecureProfile {
            get {
                return ResourceManager.GetString("Signature.LoginWithSecureProfile", resourceCulture);
            }
        }
        
        internal static string Signature_MarkIllegallySignedMsg {
            get {
                return ResourceManager.GetString("Signature.MarkIllegallySignedMsg", resourceCulture);
            }
        }
        
        internal static string Signature_MarkLegallySignedMsg {
            get {
                return ResourceManager.GetString("Signature.MarkLegallySignedMsg", resourceCulture);
            }
        }
        
        internal static string Signature_MarkModifiedMsg {
            get {
                return ResourceManager.GetString("Signature.MarkModifiedMsg", resourceCulture);
            }
        }
        
        internal static string Signature_MarkSystemMessage {
            get {
                return ResourceManager.GetString("Signature.MarkSystemMessage", resourceCulture);
            }
        }
        
        internal static string Signature_ShowIllegalSignedChat {
            get {
                return ResourceManager.GetString("Signature.ShowIllegalSignedChat", resourceCulture);
            }
        }
        
        internal static string Signature_ShowModifiedChat {
            get {
                return ResourceManager.GetString("Signature.ShowModifiedChat", resourceCulture);
            }
        }
        
        internal static string Signature_SignChat {
            get {
                return ResourceManager.GetString("Signature.SignChat", resourceCulture);
            }
        }
        
        internal static string Signature_SignMessageInCommand {
            get {
                return ResourceManager.GetString("Signature.SignMessageInCommand", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector_Collect_All_Item_Types {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector.Collect_All_Item_Types", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector_Items_Whitelist {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector.Items_Whitelist", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector_Delay_Between_Tasks {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector.Delay_Between_Tasks", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector_Collection_Radius {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector.Collection_Radius", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector_Always_Return_To_Start {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector.Always_Return_To_Start", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector_Prioritize_Clusters {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector.Prioritize_Clusters", resourceCulture);
            }
        }
        
        internal static string ChatBot_ItemsCollector {
            get {
                return ResourceManager.GetString("ChatBot.ItemsCollector", resourceCulture);
            }
        }
    }
}
