//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftClient {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigComments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigComments() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftClient.Resources.ConfigComments.ConfigComments", typeof(ConfigComments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 can be used in some other fields as %yourvar%
        ///%username% and %serverip% are reserved variables. 的當地語系化字串。
        /// </summary>
        internal static string AppVars_Variables {
            get {
                return ResourceManager.GetString("AppVars.Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 =============================== #
        /// Minecraft Console Client Bots  #
        ///=============================== # 的當地語系化字串。
        /// </summary>
        internal static string ChatBot {
            get {
                return ResourceManager.GetString("ChatBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Get alerted when specified words are detected in chat
        ///Useful for moderating your server or detecting when someone is talking to you 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts {
            get {
                return ResourceManager.GetString("ChatBot.Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Play a beep sound when a word is detected in addition to highlighting. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Beep_Enabled {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Beep_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 List of words/strings to NOT alert you on. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Excludes {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Excludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The name of a file where alers logs will be written. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Log_File {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log alerts info a file. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Log_To_File {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Log_To_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 List of words/strings to alert you on. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Matches {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Trigger alerts when it rains and when it stops. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Trigger_By_Rain {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Trigger_By_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Triggers alerts at the beginning and end of thunderstorms. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Trigger_By_Thunderstorm {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Trigger_By_Thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Triggers an alert after receiving a specified keyword. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Alerts_Trigger_By_Words {
            get {
                return ResourceManager.GetString("ChatBot.Alerts.Trigger_By_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send a command on a regular or random basis or make the bot walk around randomly to avoid automatic AFK disconnection
        ////!\ Make sure your server rules do not forbid anti-AFK mechanisms!
        ////!\ Make sure you keep the bot in an enclosure to prevent it wandering off if you&apos;re using terrain handling! (Recommended size 5x5x5) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Command to send to the server. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk_Command {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The time interval for execution. (in seconds) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to sneak when sending the command. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk_Use_Sneak {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Use_Sneak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use terrain handling to enable the bot to move around. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk_Use_Terrain_Handling {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Use_Terrain_Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The range the bot can move around randomly (Note: the bigger the range, the slower the bot will be) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk_Walk_Range {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Walk_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How many times can the bot fail trying to move before using the command method. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AntiAfk_Walk_Retries {
            get {
                return ResourceManager.GetString("ChatBot.AntiAfk.Walk_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically attack hostile mobs around you
        ///You need to enable Entity Handling to use this bot
        ////!\ Make sure server rules allow your planned use of AutoAttack
        ////!\ SERVER PLUGINS may consider AutoAttack to be a CHEAT MOD and TAKE ACTION AGAINST YOUR ACCOUNT so DOUBLE CHECK WITH SERVER RULES! 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow attacking hostile mobs. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Attack_Hostile {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Attack_Hostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow attacking passive mobs. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Attack_Passive {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Attack_Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Capped between 1 to 4 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Attack_Range {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Attack_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How long to wait between each attack. Set &quot;Custom = false&quot; to let MCC calculate it. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Cooldown_Time {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Cooldown_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All entity types can be found here: https://mccteam.github.io/r/entity/#L15 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Entites_List {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Entites_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Possible values: &quot;Interact&quot;, &quot;Attack&quot; (default), &quot;InteractAt&quot; (Interact and Attack). 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Interaction {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wether to treat the entities list as a &quot;whitelist&quot; or as a &quot;blacklist&quot;. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_List_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.List_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;single&quot; or &quot;multi&quot;. single target one mob per attack. multi target all mobs in range per attack 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;health&quot; or &quot;distance&quot;. Only needed when using single mode 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoAttack_Priority {
            get {
                return ResourceManager.GetString("ChatBot.AutoAttack.Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically craft items in your inventory
        ///See https://mccteam.github.io/g/bots/#auto-craft for how to use
        ///You need to enable Inventory Handling to use this bot
        ///You should also enable Terrain and Movements if you need to use a crafting table 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoCraft {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location of the crafting table if you intended to use it. Terrain and movements must be enabled. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoCraft_CraftingTable {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft.CraftingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 What to do on crafting failure, &quot;abort&quot; or &quot;wait&quot;. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoCraft_OnFailure {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft.OnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipes.Name: The name can be whatever you like and it is used to represent the recipe.
        ///Recipes.Type: crafting table type: &quot;player&quot; or &quot;table&quot;
        ///Recipes.Result: the resulting item
        ///Recipes.Slots: All slots, counting from left to right, top to bottom. Please fill in &quot;Null&quot; for empty slots.
        ///For the naming of the items, please see: https://mccteam.github.io/r/item/#L12 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoCraft_Recipes {
            get {
                return ResourceManager.GetString("ChatBot.AutoCraft.Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto-digging blocks.
        ///You need to enable Terrain Handling to use this bot
        ///You can use &quot;/digbot start&quot; and &quot;/digbot stop&quot; to control the start and stop of AutoDig.
        ///Since MCC does not yet support accurate calculation of the collision volume of blocks, all blocks are considered as complete cubes when obtaining the position of the lookahead.
        ///For the naming of the block, please see https://mccteam.github.io/r/block/#L15 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How many seconds to wait after entering the game to start digging automatically, set to -1 to disable automatic start. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Auto_Start_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Auto_Start_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically switch to the appropriate tool. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Auto_Tool_Switch {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Auto_Tool_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mining a block for more than &quot;Dig_Timeout&quot; seconds will be considered a timeout. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Dig_Timeout {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Dig_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to drop the current tool when its durability is too low. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Drop_Low_Durability_Tools {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Drop_Low_Durability_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Will not use tools with less durability than this. Set to zero to disable this feature. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Durability_Limit {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Durability_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wether to treat the blocks list as a &quot;whitelist&quot; or as a &quot;blacklist&quot;. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_List_Type {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.List_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;distance&quot; or &quot;index&quot;, When using the &quot;fixedpos&quot; mode, the blocks are determined by distance to the player, or by the order in the list. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Location_Order {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Location_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The position of the blocks when using &quot;fixedpos&quot; or &quot;both&quot; mode. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Locations {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to output logs when digging blocks. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Log_Block_Dig {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Log_Block_Dig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;lookat&quot;, &quot;fixedpos&quot; or &quot;both&quot;. Digging the block being looked at, the block in a fixed position, or the block that needs to be all met. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDig_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoDig.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically drop items in inventory
        ///You need to enable Inventory Handling to use this bot
        ///See this file for an up-to-date list of item types you can use with this bot: https://mccteam.github.io/r/item/#L12 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDrop {
            get {
                return ResourceManager.GetString("ChatBot.AutoDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;include&quot;, &quot;exclude&quot; or &quot;everything&quot;. Include: drop item IN the list. Exclude: drop item NOT IN the list 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoDrop_Mode {
            get {
                return ResourceManager.GetString("ChatBot.AutoDrop.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically eat food when your Hunger value is low
        ///You need to enable Inventory Handling to use this bot 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoEat {
            get {
                return ResourceManager.GetString("ChatBot.AutoEat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically catch fish using a fishing rod
        ///Guide: https://mccteam.github.io/g/bots/#auto-fishing
        ///You can use &quot;/fish&quot; to control the bot manually.
        ////!\ Make sure server rules allow automated farming before using this bot 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep it as false if you have not changed it before. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Antidespawn {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Antidespawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Switch to a new rod from inventory after the current rod is unavailable. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Auto_Rod_Switch {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Auto_Rod_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to start fishing automatically after entering a world. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Auto_Start {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Auto_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How soon to re-cast after successful fishing. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Cast_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Cast_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Will not use rods with less durability than this (full durability is 64). Set to zero to disable this feature. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Durability_Limit {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Durability_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This allows the player to change position/facing after each fish caught. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Enable_Move {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Enable_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How long after entering the game to start fishing (seconds). 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Fishing_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Fishing_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fishing timeout (seconds). Timeout will trigger a re-cast. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Fishing_Timeout {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Fishing_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A &quot;stationary&quot; hook that moves above this threshold in the Y-axis will be considered to have caught a fish. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Hook_Threshold {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Hook_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Used to adjust the above two thresholds, which when enabled will print the change in the position of the fishhook entity upon receipt of its movement packet. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Log_Fish_Bobber {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Log_Fish_Bobber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use the mainhand or the offhand to hold the rod. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Mainhand {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Mainhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 It will move in order &quot;1-&gt;2-&gt;3-&gt;4-&gt;3-&gt;2-&gt;1-&gt;2-&gt;...&quot; and can change position or facing or both each time. It is recommended to change the facing only. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Movements {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hook movement in the X and Z axis less than this value will be considered stationary. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoFishing_Stationary_Threshold {
            get {
                return ResourceManager.GetString("ChatBot.AutoFishing.Stationary_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically relog when disconnected by server, for example because the server is restating
        ////!\ Use Ignore_Kick_Message=true at own risk! Server staff might not appreciate if you auto-relog on manual kicks 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRelog {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The delay time before joining the server. (in seconds) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRelog_Delay {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When set to true, autorelog will reconnect regardless of kick messages. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRelog_Ignore_Kick_Message {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Ignore_Kick_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If the kickout message matches any of the strings, then autorelog will be triggered. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRelog_Kick_Messages {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Kick_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Retries when failing to relog to the server. use -1 for unlimited retries. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRelog_Retries {
            get {
                return ResourceManager.GetString("ChatBot.AutoRelog.Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run commands or send messages automatically when a specified pattern is detected in chat
        ///Server admins can spoof chat messages (/nick, /tellraw) so keep this in mind when implementing AutoRespond rules
        ////!\ This bot may get spammy depending on your rules, although the global messagecooldown setting can help you avoiding accidental spam 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRespond {
            get {
                return ResourceManager.GetString("ChatBot.AutoRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do not remove colors from text (Note: Your matches will have to include color codes (ones using the § character) in order to work) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_AutoRespond_Match_Colors {
            get {
                return ResourceManager.GetString("ChatBot.AutoRespond.Match_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logs chat messages in a file on disk. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_ChatLog {
            get {
                return ResourceManager.GetString("ChatBot.ChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This bot allows you to send and recieve messages and commands via a Discord channel.
        ///For Setup you can either use the documentation or read here (Documentation has images).
        ///Documentation: https://mccteam.github.io/g/bots/#discord-bridge
        ///Setup:
        ///First you need to create a Bot on the Discord Developers Portal, here is a video tutorial: https://www.youtube.com/watch?v=2FgMnZViNPA .
        ////!\ IMPORTANT /!\: When creating a bot, you MUST ENABLE &quot;Message Content Intent&quot;, &quot;Server Members Intent&quot; and &quot;Presence Intent [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The ID of a channel where you want to interact with the MCC using the bot. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge_ChannelId {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.ChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message formats
        ///Words wrapped with { and } are going to be replaced during the code execution, do not change them!
        ///For example. {message} is going to be replace with an actual message, {username} will be replaced with an username, {timestamp} with the current time.
        ///For Discord message formatting, check the following: https://mccteam.github.io/r/dc-fmt.html 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge_Formats {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The ID of a server/guild where you have invited the bot to. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge_GuildId {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.GuildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How long to wait (in seconds) if a message can not be sent to discord before canceling the task (minimum 1 second). 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge_MessageSendTimeout {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.MessageSendTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A list of IDs of people you want to be able to interact with the MCC using the bot. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge_OwnersIds {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.OwnersIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your Discord Bot token. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_DiscordBridge_Token {
            get {
                return ResourceManager.GetString("ChatBot.DiscordBridge.Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically farms crops for you (plants, breaks and bonemeals them).
        ///Crop types available: Beetroot, Carrot, Melon, Netherwart, Pumpkin, Potato, Wheat.
        ///Usage: &quot;/farmer start&quot; command and &quot;/farmer stop&quot; command.
        ///NOTE: This a newly added bot, it is not perfect and was only tested in 1.19.2, there are some minor issues like not being able to bonemeal carrots/potatoes sometimes.
        ///or bot jumps onto the farm land and breaks it (this happens rarely but still happens). We are looking forward at improving this. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Farmer {
            get {
                return ResourceManager.GetString("ChatBot.Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delay between tasks in seconds (Minimum 1 second) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Farmer_Delay_Between_Tasks {
            get {
                return ResourceManager.GetString("ChatBot.Farmer.Delay_Between_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enabled you to make the bot follow you
        ///NOTE: This is an experimental feature, the bot can be slow at times, you need to walk with a normal speed and to sometimes stop for it to be able to keep up with you
        ///It&apos;s similar to making animals follow you when you&apos;re holding food in your hand.
        ///This is due to a slow pathfinding algorithm, we&apos;re working on getting a better one
        ///You can tweak the update limit and find what works best for you. (NOTE: Do not but a very low one, because you might achieve the opposite,        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_FollowPlayer {
            get {
                return ResourceManager.GetString("ChatBot.FollowPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do not follow the player if he is in the range of 3 blocks (prevents the bot from pushing a player in an infinite loop) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_FollowPlayer_Stop_At_Distance {
            get {
                return ResourceManager.GetString("ChatBot.FollowPlayer.Stop_At_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The rate at which the bot does calculations (in seconds) (You can tweak this if you feel the bot is too slow) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_FollowPlayer_Update_Limit {
            get {
                return ResourceManager.GetString("ChatBot.FollowPlayer.Update_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A small game to demonstrate chat interactions. Players can guess mystery words one letter at a time.
        ///You need to have ChatFormat working correctly and add yourself in botowners to start the game with /tell &lt;bot username&gt; start
        ////!\ This bot may get a bit spammy if many players are interacting with it 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_HangmanGame {
            get {
                return ResourceManager.GetString("ChatBot.HangmanGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Relay messages between players and servers, like a mail plugin
        ///This bot can store messages when the recipients are offline, and send them when they join the server
        ////!\ Server admins can spoof PMs (/tellraw, /nick) so enable this bot only if you trust server admins 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Mailer {
            get {
                return ResourceManager.GetString("ChatBot.Mailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allows you to render maps in the console and into images (which can be then sent to Discord using Discord Bridge Chat Bot)
        ///This is useful for solving captchas which use maps
        ///The maps are rendered into Rendered_Maps folder if the Save_To_File is enabled.
        ///NOTE:
        ///If some servers have a very short time for solving captchas, enabe Auto_Render_On_Update to see them immediatelly in the console.
        ////!\ Make sure server rules allow bots to be used on the server, or you risk being punished. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map {
            get {
                return ResourceManager.GetString("ChatBot.Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically render the map once it is received or updated from/by the server 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Auto_Render_On_Update {
            get {
                return ResourceManager.GetString("ChatBot.Map.Auto_Render_On_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete all rendered maps on unload/reload or when you launch the MCC again. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Delete_All_On_Unload {
            get {
                return ResourceManager.GetString("ChatBot.Map.Delete_All_On_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Get a notification when you have gotten a map from the server for the first time 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Notify_On_First_Update {
            get {
                return ResourceManager.GetString("ChatBot.Map.Notify_On_First_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Resize an rendered image, this is useful when images that are rendered are small and when are being sent to Discord. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Rasize_Rendered_Image {
            get {
                return ResourceManager.GetString("ChatBot.Map.Rasize_Rendered_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to render the map in the console. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Render_In_Console {
            get {
                return ResourceManager.GetString("ChatBot.Map.Render_In_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The size that a rendered image should be resized to, in pixels (eg. 512). 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Resize_To {
            get {
                return ResourceManager.GetString("ChatBot.Map.Resize_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to store the rendered map as a file (You need this setting if you want to get a map on Discord using Discord Bridge). 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Save_To_File {
            get {
                return ResourceManager.GetString("ChatBot.Map.Save_To_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send a rendered map (saved to a file) to a Discord or a Telegram channel via the Discord or Telegram Bride chat bot (The Discord/Telegram Bridge chat bot must be enabled and configured!)
        ///You need to enable Save_To_File in order for this to work.
        ///We also recommend turning on resizing. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_Map_Send_Rendered_To_Bridges {
            get {
                return ResourceManager.GetString("ChatBot.Map.Send_Rendered_To_Bridges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log the list of players periodically into a textual file. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_PlayerListLogger {
            get {
                return ResourceManager.GetString("ChatBot.PlayerListLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (In seconds) 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_PlayerListLogger_Delay {
            get {
                return ResourceManager.GetString("ChatBot.PlayerListLogger.Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send MCC console commands to your bot through server PMs (/tell)
        ///You need to have ChatFormat working correctly and add yourself in botowners to use the bot
        ////!\ Server admins can spoof PMs (/tellraw, /nick) so enable RemoteControl only if you trust server admins 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_RemoteControl {
            get {
                return ResourceManager.GetString("ChatBot.RemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable recording of the game (/replay start) and replay it later using the Replay Mod (https://www.replaymod.com/)
        ///Please note that due to technical limitations, the client player (you) will not be shown in the replay file
        ////!\ You SHOULD use /replay stop or exit the program gracefully with /quit OR THE REPLAY FILE MAY GET CORRUPT! 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_ReplayCapture {
            get {
                return ResourceManager.GetString("ChatBot.ReplayCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How long should replay file be auto-saved, in seconds. Use -1 to disable. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_ReplayCapture_Backup_Interval {
            get {
                return ResourceManager.GetString("ChatBot.ReplayCapture.Backup_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Schedule commands and scripts to launch on various events such as server join, date/time or time interval
        ///See https://mccteam.github.io/g/bots/#script-scheduler for more info 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_ScriptScheduler {
            get {
                return ResourceManager.GetString("ChatBot.ScriptScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This bot allows you to send and receive messages and commands via a Telegram Bot DM or to receive messages in a Telegram channel.
        ////!\ NOTE: You can&apos;t send messages and commands from a group channel, you can only send them in the bot DM, but you can get the messages from the client in a group channel.
        ///-----------------------------------------------------------
        ///Setup:
        ///First you need to create a Telegram bot and obtain an API key, to do so, go to Telegram and find @botfather
        ///Click on &quot;Start&quot; button and re [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_TelegramBridge {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A list of Chat IDs that are allowed to send messages and execute commands. To get an id of your chat DM with the bot use &quot;.chatid&quot; bot command in Telegram. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_TelegramBridge_Authorized_Chat_Ids {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.Authorized_Chat_Ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An ID of a channel where you want to interact with the MCC using the bot. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_TelegramBridge_ChannelId {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.ChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message formats
        ///Words wrapped with { and } are going to be replaced during the code execution, do not change them!
        ///For example. {message} is going to be replace with an actual message, {username} will be replaced with an username, {timestamp} with the current time.
        ///For Telegram message formatting, check the following: https://mccteam.github.io/r/tg-fmt.html 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_TelegramBridge_Formats {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How long to wait (in seconds) if a message can not be sent to Telegram before canceling the task (minimum 1 second). 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_TelegramBridge_MessageSendTimeout {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.MessageSendTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your Telegram Bot token. 的當地語系化字串。
        /// </summary>
        internal static string ChatBot_TelegramBridge_Token {
            get {
                return ResourceManager.GetString("ChatBot.TelegramBridge.Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MCC does it best to detect chat messages, but some server have unusual chat formats
        ///When this happens, you&apos;ll need to configure chat format below, see https://mccteam.github.io/g/conf/#chat-format-section 的當地語系化字串。
        /// </summary>
        internal static string ChatFormat {
            get {
                return ResourceManager.GetString("ChatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MCC support for common message formats. Set &quot;false&quot; to avoid conflicts with custom formats. 的當地語系化字串。
        /// </summary>
        internal static string ChatFormat_Builtins {
            get {
                return ResourceManager.GetString("ChatFormat.Builtins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to use the custom regular expressions below for detection. 的當地語系化字串。
        /// </summary>
        internal static string ChatFormat_UserDefined {
            get {
                return ResourceManager.GetString("ChatFormat.UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Startup Config File
        ///Please do not record extraneous data in this file as it will be overwritten by MCC.
        ///
        ///New to Minecraft Console Client? Check out this document: https://mccteam.github.io/g/conf.html
        ///Want to upgrade to a newer version? See https://github.com/MCCTeam/Minecraft-Console-Client/#download 的當地語系化字串。
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This setting affects only the messages in the console. 的當地語系化字串。
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Regex for filtering chat message. 的當地語系化字串。
        /// </summary>
        internal static string Logging_ChatFilter {
            get {
                return ResourceManager.GetString("Logging.ChatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show server chat messages. 的當地語系化字串。
        /// </summary>
        internal static string Logging_ChatMessages {
            get {
                return ResourceManager.GetString("Logging.ChatMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Regex for filtering debug message. 的當地語系化字串。
        /// </summary>
        internal static string Logging_DebugFilter {
            get {
                return ResourceManager.GetString("Logging.DebugFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enable this before submitting bug reports. Thanks! 的當地語系化字串。
        /// </summary>
        internal static string Logging_DebugMessages {
            get {
                return ResourceManager.GetString("Logging.DebugMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show error messages. 的當地語系化字串。
        /// </summary>
        internal static string Logging_ErrorMessages {
            get {
                return ResourceManager.GetString("Logging.ErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;disable&quot; or &quot;blacklist&quot; OR &quot;whitelist&quot;. Blacklist hide message match regex. Whitelist show message match regex. 的當地語系化字串。
        /// </summary>
        internal static string Logging_FilterMode {
            get {
                return ResourceManager.GetString("Logging.FilterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Informative messages. (i.e Most of the message from MCC) 的當地語系化字串。
        /// </summary>
        internal static string Logging_InfoMessages {
            get {
                return ResourceManager.GetString("Logging.InfoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log file name. 的當地語系化字串。
        /// </summary>
        internal static string Logging_LogFile {
            get {
                return ResourceManager.GetString("Logging.LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Write log messages to file. 的當地語系化字串。
        /// </summary>
        internal static string Logging_LogToFile {
            get {
                return ResourceManager.GetString("Logging.LogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prepend timestamp to messages in log file. 的當地語系化字串。
        /// </summary>
        internal static string Logging_PrependTimestamp {
            get {
                return ResourceManager.GetString("Logging.PrependTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep color codes in the saved text.(look like &quot;§b&quot;) 的當地語系化字串。
        /// </summary>
        internal static string Logging_SaveColorCodes {
            get {
                return ResourceManager.GetString("Logging.SaveColorCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show warning messages. 的當地語系化字串。
        /// </summary>
        internal static string Logging_WarningMessages {
            get {
                return ResourceManager.GetString("Logging.WarningMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Make sure you understand what each setting does before changing anything! 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced {
            get {
                return ResourceManager.GetString("Main.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountList: It allows a fast account switching without directly using the credentials
        ///Usage examples: &quot;/tell &lt;mybot&gt; reco Player2&quot;, &quot;/connect &lt;serverip&gt; Player1&quot; 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_account_list {
            get {
                return ResourceManager.GetString("Main.Advanced.account_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle auto respawn if client player was dead (make sure your spawn point is safe). 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_auto_respawn {
            get {
                return ResourceManager.GetString("Main.Advanced.auto_respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set the owner of the bot. /!\ Server admins can impersonate owners! 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_bot_owners {
            get {
                return ResourceManager.GetString("Main.Advanced.bot_owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;mcc&quot;, &quot;vanilla&quot; or &quot;none&quot;. This is how MCC identifies itself to the server. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_brand_info {
            get {
                return ResourceManager.GetString("Main.Advanced.brand_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Leave empty for no logfile. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_chatbot_log_file {
            get {
                return ResourceManager.GetString("Main.Advanced.chatbot_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If turned off, the emoji will be replaced with a simpler character (for /chunk status). 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_enable_emoji {
            get {
                return ResourceManager.GetString("Main.Advanced.enable_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle entity handling. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_entity_handling {
            get {
                return ResourceManager.GetString("Main.Advanced.entity_handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to exit directly when an error occurs, for using MCC in non-interactive scripts. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_exit_on_failure {
            get {
                return ResourceManager.GetString("Main.Advanced.exit_on_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;none&quot;, &quot;slash&quot;(/) or &quot;backslash&quot;(\). 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_internal_cmd_char {
            get {
                return ResourceManager.GetString("Main.Advanced.internal_cmd_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle inventory handling. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_inventory_handling {
            get {
                return ResourceManager.GetString("Main.Advanced.inventory_handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill in with in-game locale code, check https://mccteam.github.io/r/l-code.html 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_language {
            get {
                return ResourceManager.GetString("Main.Advanced.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load translations applied to MCC when available, turn it off to use English only. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_LoadMccTrans {
            get {
                return ResourceManager.GetString("Main.Advanced.LoadMccTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;auto&quot;, &quot;no&quot; or &quot;force&quot;. Force-enabling only works for MC 1.13+. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_mc_forge {
            get {
                return ResourceManager.GetString("Main.Advanced.mc_forge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;auto&quot; or &quot;1.X.X&quot; values. Allows to skip server info retrieval. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_mc_version {
            get {
                return ResourceManager.GetString("Main.Advanced.mc_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controls the minimum interval (in seconds) between sending each message to the server. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_message_cooldown {
            get {
                return ResourceManager.GetString("Main.Advanced.message_cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable support for joining Minecraft Realms worlds. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_minecraft_realms {
            get {
                return ResourceManager.GetString("Main.Advanced.minecraft_realms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The minimum height to use when calculating the image size from the height of the terminal. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_MinTerminalHeight {
            get {
                return ResourceManager.GetString("Main.Advanced.MinTerminalHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The minimum width used when calculating the image size from the width of the terminal. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_MinTerminalWidth {
            get {
                return ResourceManager.GetString("Main.Advanced.MinTerminalWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable head movement while walking to avoid anti-cheat triggers. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_move_head_while_walking {
            get {
                return ResourceManager.GetString("Main.Advanced.move_head_while_walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A movement speed higher than 2 may be considered cheating. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_movement_speed {
            get {
                return ResourceManager.GetString("Main.Advanced.movement_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Only works on Windows XP-8 or Windows 10 with old console. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_player_head_icon {
            get {
                return ResourceManager.GetString("Main.Advanced.player_head_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 For remote control of the bot. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_private_msgs_cmd_name {
            get {
                return ResourceManager.GetString("Main.Advanced.private_msgs_cmd_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How to retain profile key. Use &quot;none&quot;, &quot;memory&quot; or &quot;disk&quot;. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_profilekey_cache {
            get {
                return ResourceManager.GetString("Main.Advanced.profilekey_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;no&quot;, &quot;fast&quot; (5s timeout), or &quot;yes&quot;. Required for joining some servers. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_resolve_srv_records {
            get {
                return ResourceManager.GetString("Main.Advanced.resolve_srv_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cache compiled scripts for faster load on low-end devices. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_script_cache {
            get {
                return ResourceManager.GetString("Main.Advanced.script_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ServerList: It allows an easier and faster server switching with short aliases instead of full server IP
        ///Aliases cannot contain dots or spaces, and the name &quot;localhost&quot; cannot be used as an alias.
        ///Usage examples: &quot;/tell &lt;mybot&gt; connect Server1&quot;, &quot;/connect Server2&quot; 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_server_list {
            get {
                return ResourceManager.GetString("Main.Advanced.server_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How to retain session tokens. Use &quot;none&quot;, &quot;memory&quot; or &quot;disk&quot;. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_session_cache {
            get {
                return ResourceManager.GetString("Main.Advanced.session_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Decode links embedded in chat messages and show them in console. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_show_chat_links {
            get {
                return ResourceManager.GetString("Main.Advanced.show_chat_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show inventory layout as ASCII art in inventory command. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_show_inventory_layout {
            get {
                return ResourceManager.GetString("Main.Advanced.show_inventory_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System messages for server ops. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_show_system_messages {
            get {
                return ResourceManager.GetString("Main.Advanced.show_system_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Messages displayed above xp bar, set this to false in case of xp bar spam. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_show_xpbar_messages {
            get {
                return ResourceManager.GetString("Main.Advanced.show_xpbar_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Temporary fix for Badpacket issue on some servers. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_temporary_fix_badpacket {
            get {
                return ResourceManager.GetString("Main.Advanced.temporary_fix_badpacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;none&quot;, &quot;bit_4&quot;, &quot;bit_8&quot; or &quot;bit_24&quot;. This can be checked by opening the debug log. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_TerminalColorDepth {
            get {
                return ResourceManager.GetString("Main.Advanced.TerminalColorDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uses more ram, cpu, bandwidth but allows you to move around. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_terrain_and_movements {
            get {
                return ResourceManager.GetString("Main.Advanced.terrain_and_movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customize the TCP connection timeout with the server. (in seconds) 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_timeout {
            get {
                return ResourceManager.GetString("Main.Advanced.timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prepend timestamps to chat messages. 的當地語系化字串。
        /// </summary>
        internal static string Main_Advanced_timestamps {
            get {
                return ResourceManager.GetString("Main.Advanced.timestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login=Email or Name. Use &quot;-&quot; as password for offline mode. Leave blank to prompt user on startup. 的當地語系化字串。
        /// </summary>
        internal static string Main_General_account {
            get {
                return ResourceManager.GetString("Main.General.account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The address of the game server, &quot;Host&quot; can be filled in with domain name or IP address. (The &quot;Port&quot; field can be deleted, it will be resolved automatically) 的當地語系化字串。
        /// </summary>
        internal static string Main_General_login {
            get {
                return ResourceManager.GetString("Main.General.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft Account sign-in method: &quot;mcc&quot; OR &quot;browser&quot;. If the login always fails, please try to use the &quot;browser&quot; once. 的當地語系化字串。
        /// </summary>
        internal static string Main_General_method {
            get {
                return ResourceManager.GetString("Main.General.method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account type: &quot;mojang&quot; OR &quot;microsoft&quot;. Also affects interactive login in console. 的當地語系化字串。
        /// </summary>
        internal static string Main_General_server_info {
            get {
                return ResourceManager.GetString("Main.General.server_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings below are sent to the server and only affect server-side things like your skin. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings {
            get {
                return ResourceManager.GetString("MCSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allows disabling chat colors server-side. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_ChatColors {
            get {
                return ResourceManager.GetString("MCSettings.ChatColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use &quot;enabled&quot;, &quot;commands&quot;, or &quot;disabled&quot;. Allows to mute yourself... 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_ChatMode {
            get {
                return ResourceManager.GetString("MCSettings.ChatMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MC 1.7- difficulty. &quot;peaceful&quot;, &quot;easy&quot;, &quot;normal&quot;, &quot;difficult&quot;. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_Difficulty {
            get {
                return ResourceManager.GetString("MCSettings.Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If disabled, settings below are not sent to the server. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_Enabled {
            get {
                return ResourceManager.GetString("MCSettings.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use any language implemented in Minecraft. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_Locale {
            get {
                return ResourceManager.GetString("MCSettings.Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MC 1.9+ main hand. &quot;left&quot; or &quot;right&quot;. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_MainHand {
            get {
                return ResourceManager.GetString("MCSettings.MainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value range: [0 - 255]. 的當地語系化字串。
        /// </summary>
        internal static string MCSettings_RenderDistance {
            get {
                return ResourceManager.GetString("MCSettings.RenderDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect to a server via a proxy instead of connecting directly
        ///If Mojang session services are blocked on your network, set Enabled_Login=true to login using proxy.
        ///If the connection to the Minecraft game server is blocked by the firewall, set Enabled_Ingame=true to use a proxy to connect to the game server.
        ////!\ Make sure your server rules allow Proxies or VPNs before setting enabled=true, or you may face consequences! 的當地語系化字串。
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to connect to the game server through a proxy. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Enabled_Ingame {
            get {
                return ResourceManager.GetString("Proxy.Enabled_Ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to connect to the login server through a proxy. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Enabled_Login {
            get {
                return ResourceManager.GetString("Proxy.Enabled_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to download MCC updates via proxy. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Enabled_Update {
            get {
                return ResourceManager.GetString("Proxy.Enabled_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Only required for password-protected proxies. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Password {
            get {
                return ResourceManager.GetString("Proxy.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Supported types: &quot;HTTP&quot;, &quot;SOCKS4&quot;, &quot;SOCKS4a&quot;, &quot;SOCKS5&quot;. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Proxy_Type {
            get {
                return ResourceManager.GetString("Proxy.Proxy_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Proxy server must allow HTTPS for login, and non-443 ports for playing. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Server {
            get {
                return ResourceManager.GetString("Proxy.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Only required for password-protected proxies. 的當地語系化字串。
        /// </summary>
        internal static string Proxy_Username {
            get {
                return ResourceManager.GetString("Proxy.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chat signature related settings (affects minecraft 1.19+) 的當地語系化字串。
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft accounts only. If disabled, will not be able to sign chat and join servers configured with &quot;enforce-secure-profile=true&quot; 的當地語系化字串。
        /// </summary>
        internal static string Signature_LoginWithSecureProfile {
            get {
                return ResourceManager.GetString("Signature.LoginWithSecureProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use red    color block to mark chat without legitimate signature 的當地語系化字串。
        /// </summary>
        internal static string Signature_MarkIllegallySignedMsg {
            get {
                return ResourceManager.GetString("Signature.MarkIllegallySignedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use green  color block to mark chat with legitimate signatures 的當地語系化字串。
        /// </summary>
        internal static string Signature_MarkLegallySignedMsg {
            get {
                return ResourceManager.GetString("Signature.MarkLegallySignedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use yellow color block to mark chat that have been modified by the server. 的當地語系化字串。
        /// </summary>
        internal static string Signature_MarkModifiedMsg {
            get {
                return ResourceManager.GetString("Signature.MarkModifiedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use gray   color block to mark system message (always without signature) 的當地語系化字串。
        /// </summary>
        internal static string Signature_MarkSystemMessage {
            get {
                return ResourceManager.GetString("Signature.MarkSystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to display chat and messages in commands without legal signatures 的當地語系化字串。
        /// </summary>
        internal static string Signature_ShowIllegalSignedChat {
            get {
                return ResourceManager.GetString("Signature.ShowIllegalSignedChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set to true to display messages modified by the server, false to display the original signed messages 的當地語系化字串。
        /// </summary>
        internal static string Signature_ShowModifiedChat {
            get {
                return ResourceManager.GetString("Signature.ShowModifiedChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to sign the chat send from MCC 的當地語系化字串。
        /// </summary>
        internal static string Signature_SignChat {
            get {
                return ResourceManager.GetString("Signature.SignChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Whether to sign the messages contained in the commands sent by MCC. For example, the message in &quot;/msg&quot; and &quot;/me&quot; 的當地語系化字串。
        /// </summary>
        internal static string Signature_SignMessageInCommand {
            get {
                return ResourceManager.GetString("Signature.SignMessageInCommand", resourceCulture);
            }
        }
    }
}
