//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultConfigResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultConfigResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftClient.DefaultConfigResource", typeof(DefaultConfigResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║            Brewing Stand            ║
        ///║  ╔═══╗      ⡈ ⠄╔═══╗                ║
        ///║  ║ 4 ╟───╮  ⢠⡐⢈║ 3 ║ ┃              ║
        ///║  ╚═══╝ ╭─╯  ⠂⡠⢂╚╦╦╦╝ ┃              ║
        ///║        ╰───■■■■ ║║║  ▼              ║
        ///║           ╔═══╦═╝║╚═╦═══╗           ║
        ///║           ║ 0 ║╔═╩═╗║ 2 ║           ║
        ///║           ╚═══╝║ 1 ║╚═══╝           ║
        ///║ Inventory      ╚═══╝                ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 5 ║ 6 ║ 7 ║ 8 ║ 9 ║10 ║11 ║12 ║13 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContainerType_BrewingStand {
            get {
                return ResourceManager.GetString("ContainerType_BrewingStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║        Crafting                     ║
        ///║       ╔═══╦═══╦═══╗                 ║
        ///║       ║ 1 ║ 2 ║ 3 ║                 ║
        ///║       ╠═══╬═══╬═══╣     ╔═══╗       ║
        ///║       ║ 4 ║ 5 ║ 6 ║ ━━▶ ║ 0 ║       ║
        ///║       ╠═══╬═══╬═══╣     ╚═══╝       ║
        ///║       ║ 7 ║ 8 ║ 9 ║                 ║
        ///║       ╚═══╩═══╩═══╝                 ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║18 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContainerType_Crafting {
            get {
                return ResourceManager.GetString("ContainerType_Crafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║             Container               ║
        ///║            ╔═══╦═══╦═══╗            ║
        ///║            ║ 0 ║ 1 ║ 2 ║            ║
        ///║            ╠═══╬═══╬═══╣            ║
        ///║            ║ 3 ║ 4 ║ 5 ║            ║
        ///║            ╠═══╬═══╬═══╣            ║
        ///║            ║ 6 ║ 7 ║ 8 ║            ║
        ///║            ╚═══╩═══╩═══╝            ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContainerType_Generic_3x3 {
            get {
                return ResourceManager.GetString("ContainerType_Generic_3x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║ Chest                               ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 0 ║ 1 ║ 2 ║ 3 ║ 4 ║ 5 ║ 6 ║ 7 ║ 8 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║18 ║19 ║20 ║21 ║22 ║23 ║24 ║25 ║26 ║║
        ///║╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║27 ║28 ║29 ║30 ║31 ║32 ║33 ║34 ║35 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContainerType_Generic_9x3 {
            get {
                return ResourceManager.GetString("ContainerType_Generic_9x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║ Large Container                     ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 0 ║ 1 ║ 2 ║ 3 ║ 4 ║ 5 ║ 6 ║ 7 ║ 8 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║18 ║19 ║20 ║21 ║22 ║23 ║24 ║25 ║26 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║27 ║28 ║29 ║30 ║31 ║32 ║33 ║34 ║35 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║36 ║37 ║38 ║39 ║40 ║41 ║42 ║43 ║44 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContainerType_Generic_9x6 {
            get {
                return ResourceManager.GetString("ContainerType_Generic_9x6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║╔═══╦═══════════╗                    ║
        ///║║ 5 ║    ███    ║   ╔═══╦═══╗        ║
        ///║╠═══╣    ███    ║   ║ 1 ║ 2 ║   ╔═══╗║
        ///║║ 6 ║  ███████  ║   ╠═══╬═══╣━━▶║ 0 ║║
        ///║╠═══╣  ███████  ║   ║ 3 ║ 4 ║   ╚═══╝║
        ///║║ 7 ║  ███████  ║   ╚═══╩═══╝        ║
        ///║╠═══╣    ███    ╠═══╗                ║
        ///║║ 8 ║    ███    ║45 ║                ║
        ///║╚═══╩═══════════╩═══╝                ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContainerType_PlayerInventory {
            get {
                return ResourceManager.GetString("ContainerType_PlayerInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Startup Config File
        ///
        ///[Main]
        ///
        ///# General settings
        ///# Leave blank to prompt user on startup
        ///# Use &quot;-&quot; as password for offline mode
        ///
        ///login=
        ///password=
        ///serverip=
        ///type=mojang                        # Account type. mojang or microsoft
        ///method=mcc                         # Microsoft Account sign-in method. mcc OR browser
        ///
        ///# Advanced settings
        ///
        ///language=en_GB
        ///consoletitle=%username%@%serverip% - Minecraft Console Client
        ///internalcmdchar=slash              # Use &apos;none&apos;, &apos;slash&apos; or &apos;backslash&apos;
        ///messagec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MinecraftClient {
            get {
                return ResourceManager.GetString("MinecraftClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [mcc]
        ///# Messages from MCC itself
        ///mcc.login=Login :
        ///mcc.login_basic_io=Please type the username or email of your choice.
        ///mcc.password=Password : 
        ///mcc.password_basic_io=Please type the password for {0}.
        ///mcc.password_hidden=Password : {0}
        ///mcc.offline=§8You chose to run in offline mode.
        ///mcc.session_invalid=§8Cached session is invalid or expired.
        ///mcc.session_valid=§8Cached session is still valid for {0}.
        ///mcc.connecting=Connecting to {0}...
        ///mcc.ip=Server IP : 
        ///mcc.use_version=§8Using Minecraft version [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TranslationEnglish {
            get {
                return ResourceManager.GetString("TranslationEnglish", resourceCulture);
            }
        }
    }
}
