#!/usr/bin/env python3
"""Generate string accessors from this repository's authoritative resource file."""
import argparse,re,html,sys
from pathlib import Path
import xml.etree.ElementTree as ET

def generate(resource, output, namespace, name, fallback=None):
    values={e.attrib['name']:e.findtext('value','') for e in ET.parse(resource).getroot().findall('data')}
    lines=['// <auto-generated />', '#nullable enable', 'using System.Globalization;', 'using System.Resources;',
           'namespace '+namespace+';', '/// <summary>Repository-owned localized strings.</summary>', 'public static class '+name, '{',
           '    private static readonly ResourceManager Resources = new("'+namespace+'.Resources.'+name+'", typeof('+name+').Assembly);']
    if fallback:
        lines+=['    /// <summary>The current execution-context resource culture.</summary>', '    public static CultureInfo? Culture { get => '+fallback+'.Culture; set => '+fallback+'.Culture = value; }']
    else:
        lines+=['    private static readonly System.Threading.AsyncLocal<CultureInfo?> Ambient = new();',
                '    /// <summary>The current execution-context resource culture.</summary>', '    public static CultureInfo? Culture { get => Ambient.Value; set => Ambient.Value = value; }']
    extra=' ?? '+fallback+'.Get(key)' if fallback else ' ?? key'
    lines+=['    /// <summary>Resolves a key through the culture fallback chain.</summary>', '    public static string Get(string key) => Resources.GetString(key, Culture)'+extra+';',
            '    /// <summary>Resolves a key against an explicit culture.</summary>', '    public static string? GetExact(string key, CultureInfo culture) => Resources.GetString(key, culture)'+(' ?? '+fallback+'.GetExact(key, culture)' if fallback else '')+';',
            '    /// <summary>Formats a localized message.</summary>', '    public static string Format(string key, params object?[] args) => string.Format(CultureInfo.CurrentCulture, Get(key), args);']
    for key,value in sorted(values.items()):
        prop=re.sub(r'[^A-Za-z0-9_]', '_', key)
        if prop[0].isdigit():prop='_'+prop
        lines+=['    /// <summary>'+html.escape(value).replace('\n',' ').replace('\r',' ')+'</summary>', '    public static string '+prop+' => Get("'+key+'");']
    lines+=['}', '']
    content='\n'.join(lines)
    if args.check:
        if not output.exists() or output.read_text()!=content:raise SystemExit('Generated resource file is stale: '+str(output))
    else:output.write_text(content)

args=argparse.ArgumentParser();args.add_argument('--check',action='store_true');args=args.parse_args()
root=Path(__file__).resolve().parents[2]
if (root/'src/DMCBK.Core').exists():
    base=root/'src/DMCBK.Core/Localization';generate(base/'Resources/McStrings.resx',base/'McStrings.Designer.cs','DMCBK.Core.Localization','McStrings')
else:
    base=root/'src/Mcc.Cli/Localization';generate(base/'Resources/MccStrings.resx',base/'MccStrings.Designer.cs','Mcc.Cli.Localization','MccStrings','DMCBK.Core.Localization.McStrings')
