// <auto-generated>
//     GENERATED by tools/gen_translations.py from Archive/MinecraftClient/Resources/AsciiArt/AsciiArt.resx.
// </auto-generated>

#nullable enable

using System.Resources;

namespace Mcc.Cli.Localization;

/// <summary>
/// The container-layout diagrams the inventory listing prints above its slot lines. Legacy keys them by
/// its own ContainerType enum; the new client keys windows by the vanilla <c>minecraft:menu</c> registry
/// id, so <see cref="ForMenuType"/> does that mapping in one place instead of at the call site.
/// </summary>
public static class ContainerArt
{
    private const string BaseName = "Mcc.Cli.Localization.Resources.ContainerArt";

    private static readonly ResourceManager Resources = new(BaseName, typeof(ContainerArt).Assembly);

    /// <summary>The diagram for a resource key, or null when that container has none.</summary>
    public static string? Get(string key) => Resources.GetString(key);

    /// <summary>The player's own window.</summary>
    public static string? PlayerInventory => Get("Container_PlayerInventory");

    /// <summary>
    /// The diagram for a vanilla menu-registry id (<c>minecraft:generic_9x3</c>, <c>minecraft:furnace</c>,
    /// ...), or null when that container type has no diagram. Mirrors legacy's
    /// ContainerTypeExtensions.GetAsciiArt (Inventory/ContainerTypeExtensions.cs:52-88) case for case,
    /// including the types it deliberately returns null for (merchant, beacon, anvil, loom, stonecutter,
    /// lectern, cartography, smithing, and the 9x1/9x2/9x4/9x5 generics).
    /// </summary>
    public static string? ForMenuType(string? menuType)
    {
        if (string.IsNullOrEmpty(menuType))
        {
            return null;
        }

        string id = menuType.StartsWith("minecraft:", StringComparison.Ordinal) ? menuType[10..] : menuType;
        return id switch
        {
            "generic_9x1" => Get("Container.Generic_9x1"),
            "generic_9x2" => Get("Container.Generic_9x2"),
            "generic_9x3" or "shulker_box" => Get("Container.Generic_9x3"),
            "generic_9x4" => Get("Container.Generic_9x4"),
            "generic_9x5" => Get("Container.Generic_9x5"),
            "generic_9x6" => Get("Container.Generic_9x6"),
            "generic_3x3" or "crafter_3x3" => Get("Container.Generic_3x3"),
            "crafting" => Get("Container.Crafting"),
            "furnace" or "blast_furnace" or "smoker" => Get("Container.Furnace"),
            "enchantment" => Get("Container.EnchantingTable"),
            "brewing_stand" => Get("Container.BrewingStand"),
            "hopper" => Get("Container.Hopper"),
            "grindstone" => Get("Container.Grindstone"),
            // Diagrams legacy left null; drawn now in the same style.
            "anvil" or "smithing" => Get("Container.Anvil"),
            "merchant" => Get("Container.Merchant"),
            "cartography_table" => Get("Container.Cartography"),
            "smithing_table" => Get("Container.SmithingTable"),
            "stonecutter" => Get("Container.Stonecutter"),
            "beacon" => Get("Container.Beacon"),
            "lectern" => Get("Container.Lectern"),
            "loom" => Get("Container.Loom"),
            _ => null,
        };
    }
}
