// <auto-generated />
#nullable enable
using System.Globalization;
using System.Resources;
namespace Mcc.Cli.Localization;
/// <summary>Repository-owned localized strings.</summary>
public static class MccStrings
{
    private static readonly ResourceManager Resources = new("Mcc.Cli.Localization.Resources.MccStrings", typeof(MccStrings).Assembly);
    /// <summary>The current execution-context resource culture.</summary>
    public static CultureInfo? Culture { get => DMCBK.Core.Localization.McStrings.Culture; set => DMCBK.Core.Localization.McStrings.Culture = value; }
    /// <summary>Resolves a key through the culture fallback chain.</summary>
    public static string Get(string key) => Resources.GetString(key, Culture) ?? DMCBK.Core.Localization.McStrings.Get(key);
    /// <summary>Resolves a key against an explicit culture.</summary>
    public static string? GetExact(string key, CultureInfo culture) => Resources.GetString(key, culture) ?? DMCBK.Core.Localization.McStrings.GetExact(key, culture);
    /// <summary>Formats a localized message.</summary>
    public static string Format(string key, params object?[] args) => string.Format(CultureInfo.CurrentCulture, Get(key), args);
    /// <summary>Open the TUI management menu.</summary>
    public static string cli_menu_description => Get("cli.menu.description");
    /// <summary>This browser needs the TUI. Use the command without &#x27;ui&#x27; for the text version.</summary>
    public static string cli_menu_unavailable => Get("cli.menu.unavailable");
    /// <summary>open the main launcher for MCC management workspaces</summary>
    public static string cli_menu_usage => Get("cli.menu.usage");
    /// <summary>Marketplace validation failed: {0}</summary>
    public static string marketplace_validation_failure => Get("marketplace.validation.failure");
    /// <summary>Validated marketplace {0} ({1} plugins).</summary>
    public static string marketplace_validation_success => Get("marketplace.validation.success");
    /// <summary>Usage: --validate-marketplace &lt;index-file-or-marketplace-folder&gt;</summary>
    public static string marketplace_validation_usage => Get("marketplace.validation.usage");
    /// <summary>Close</summary>
    public static string tui_book_close => Get("tui.book.close");
    /// <summary>Delete</summary>
    public static string tui_book_delete => Get("tui.book.delete");
    /// <summary>PageUp/PageDown: previous/next page</summary>
    public static string tui_book_edit_shortcut_tip => Get("tui.book.edit_shortcut_tip");
    /// <summary>Editing writable book.</summary>
    public static string tui_book_editing => Get("tui.book.editing");
    /// <summary>Insert</summary>
    public static string tui_book_insert => Get("tui.book.insert");
    /// <summary>Next</summary>
    public static string tui_book_next => Get("tui.book.next");
    /// <summary>Book page {0}/{1}</summary>
    public static string tui_book_page_header => Get("tui.book.page_header");
    /// <summary>PageUp/PageDown: previous/next page</summary>
    public static string tui_book_page_shortcut_tip => Get("tui.book.page_shortcut_tip");
    /// <summary>Prev</summary>
    public static string tui_book_prev => Get("tui.book.prev");
    /// <summary>Reading book.</summary>
    public static string tui_book_reading => Get("tui.book.reading");
    /// <summary>Save</summary>
    public static string tui_book_save => Get("tui.book.save");
    /// <summary>Book packet could not be sent.</summary>
    public static string tui_book_save_failed => Get("tui.book.save_failed");
    /// <summary>Saved.</summary>
    public static string tui_book_saved => Get("tui.book.saved");
    /// <summary>Sign</summary>
    public static string tui_book_sign => Get("tui.book.sign");
    /// <summary>Signed.</summary>
    public static string tui_book_signed => Get("tui.book.signed");
    /// <summary>Title</summary>
    public static string tui_book_title_watermark => Get("tui.book.title_watermark");
    /// <summary>Bottle {0}</summary>
    public static string tui_brewing_bottle => Get("tui.brewing.bottle");
    /// <summary>Fuel</summary>
    public static string tui_brewing_fuel => Get("tui.brewing.fuel");
    /// <summary>Ingredient</summary>
    public static string tui_brewing_ingredient => Get("tui.brewing.ingredient");
    /// <summary>Container</summary>
    public static string tui_container_label => Get("tui.container.label");
    /// <summary>Crafting</summary>
    public static string tui_crafting_grid => Get("tui.crafting.grid");
    /// <summary>Input cleared. Press Ctrl+C again to quit.</summary>
    public static string tui_ctrlc_input_cleared => Get("tui.ctrlc_input_cleared");
    /// <summary>Press Ctrl+C again to quit MCC.</summary>
    public static string tui_ctrlc_quit_hint => Get("tui.ctrlc_quit_hint");
    /// <summary>Cancel</summary>
    public static string tui_dialog_cancel => Get("tui.dialog.cancel");
    /// <summary>Item</summary>
    public static string tui_enchanting_item => Get("tui.enchanting.item");
    /// <summary>Lapis</summary>
    public static string tui_enchanting_lapis => Get("tui.enchanting.lapis");
    /// <summary>Option {0}</summary>
    public static string tui_enchanting_option_slot => Get("tui.enchanting.option_slot");
    /// <summary>Enchant Options</summary>
    public static string tui_enchanting_options => Get("tui.enchanting.options");
    /// <summary>Fuel</summary>
    public static string tui_furnace_fuel => Get("tui.furnace.fuel");
    /// <summary>Input</summary>
    public static string tui_furnace_input => Get("tui.furnace.input");
    /// <summary>Output</summary>
    public static string tui_furnace_output => Get("tui.furnace.output");
    /// <summary>Input 1</summary>
    public static string tui_grindstone_input1 => Get("tui.grindstone.input1");
    /// <summary>Input 2</summary>
    public static string tui_grindstone_input2 => Get("tui.grindstone.input2");
    /// <summary>Container not found</summary>
    public static string tui_inventory_container_not_found => Get("tui.inventory.container_not_found");
    /// <summary>[ Controls ]</summary>
    public static string tui_inventory_controls => Get("tui.inventory.controls");
    /// <summary>LClick  Pick/Place RClick  Half/Place1 Shift+C QuickMove Q       Drop x1 Ctrl+Q  Drop Stack R       Refresh E/ESC   Exit</summary>
    public static string tui_inventory_controls_help => Get("tui.inventory.controls_help");
    /// <summary>(empty)</summary>
    public static string tui_inventory_cursor_empty => Get("tui.inventory.cursor_empty");
    /// <summary>Durability</summary>
    public static string tui_inventory_durability => Get("tui.inventory.durability");
    /// <summary>Bd</summary>
    public static string tui_inventory_equip_body => Get("tui.inventory.equip_body");
    /// <summary>Ft</summary>
    public static string tui_inventory_equip_feet => Get("tui.inventory.equip_feet");
    /// <summary>Hd</summary>
    public static string tui_inventory_equip_head => Get("tui.inventory.equip_head");
    /// <summary>Lg</summary>
    public static string tui_inventory_equip_legs => Get("tui.inventory.equip_legs");
    /// <summary>[ Held Item ]</summary>
    public static string tui_inventory_held_item => Get("tui.inventory.held_item");
    /// <summary>Hover over a slot to see item details.</summary>
    public static string tui_inventory_hover_hint => Get("tui.inventory.hover_hint");
    /// <summary>{0} items</summary>
    public static string tui_inventory_item_count => Get("tui.inventory.item_count");
    /// <summary>[ Item Info ]</summary>
    public static string tui_inventory_item_info => Get("tui.inventory.item_info");
    /// <summary>Off</summary>
    public static string tui_inventory_offhand => Get("tui.inventory.offhand");
    /// <summary>Out</summary>
    public static string tui_inventory_output => Get("tui.inventory.output");
    /// <summary>Slot #{0}  Count: {1}</summary>
    public static string tui_inventory_slot_detail => Get("tui.inventory.slot_detail");
    /// <summary>(Empty)</summary>
    public static string tui_inventory_slot_empty => Get("tui.inventory.slot_empty");
    /// <summary>Inventory #{0} - {1}</summary>
    public static string tui_inventory_title => Get("tui.inventory.title");
    /// <summary>Hostile</summary>
    public static string tui_minimap_legend_hostile => Get("tui.minimap.legend.hostile");
    /// <summary>Neutral</summary>
    public static string tui_minimap_legend_neutral => Get("tui.minimap.legend.neutral");
    /// <summary>Passive</summary>
    public static string tui_minimap_legend_passive => Get("tui.minimap.legend.passive");
    /// <summary>Player</summary>
    public static string tui_minimap_legend_player => Get("tui.minimap.legend.player");
    /// <summary>Empty plugin graph</summary>
    public static string tui_plugins_empty_graph => Get("tui.plugins.empty_graph");
    /// <summary>SHA-256</summary>
    public static string tui_plugins_hash => Get("tui.plugins.hash");
    /// <summary>Include prereleases</summary>
    public static string tui_plugins_prerelease => Get("tui.plugins.prerelease");
    /// <summary>Rollback</summary>
    public static string tui_plugins_rollback => Get("tui.plugins.rollback");
    /// <summary>Package graph restored.</summary>
    public static string tui_plugins_rollback_done => Get("tui.plugins.rollback_done");
    /// <summary>No completed transactions are available.</summary>
    public static string tui_plugins_rollback_empty => Get("tui.plugins.rollback_empty");
    /// <summary>Restore the package graph from before a completed transaction. Settings and plugin data are preserved.</summary>
    public static string tui_plugins_rollback_help => Get("tui.plugins.rollback_help");
    /// <summary>Prefer source</summary>
    public static string tui_plugins_source => Get("tui.plugins.source");
    /// <summary>Allow source fallback for mixed releases</summary>
    public static string tui_plugins_source_fallback => Get("tui.plugins.source_fallback");
    /// <summary>Target</summary>
    public static string tui_plugins_target => Get("tui.plugins.target");
    /// <summary>Version</summary>
    public static string tui_plugins_version => Get("tui.plugins.version");
    /// <summary>Choose an exact version and publisher. Required dependencies are reviewed before installation.</summary>
    public static string tui_plugins_version_help => Get("tui.plugins.version_help");
    /// <summary>Versions</summary>
    public static string tui_plugins_versions => Get("tui.plugins.versions");
    /// <summary>Yanked</summary>
    public static string tui_plugins_yanked => Get("tui.plugins.yanked");
    /// <summary>Hold Shift + Left-click to select and copy text.</summary>
    public static string tui_select_copy_hint => Get("tui.select_copy_hint");
    /// <summary>Press Esc to close. Refreshes automatically.</summary>
    public static string tui_tab_hint => Get("tui.tab.hint");
}
