/* This file is automatically generated by "gen_configs.py" */
import type { SiteLocaleConfig } from '@vuepress/shared'
import type { LocaleConfig } from '@vuepress/shared'

import { mainConfig_af, defaultThemeConfig_af } from './l10n_configs/af.js'
import { mainConfig_ar, defaultThemeConfig_ar } from './l10n_configs/ar.js'
import { mainConfig_ca, defaultThemeConfig_ca } from './l10n_configs/ca.js'
import { mainConfig_cs, defaultThemeConfig_cs } from './l10n_configs/cs.js'
import { mainConfig_da, defaultThemeConfig_da } from './l10n_configs/da.js'
import { mainConfig_de, defaultThemeConfig_de } from './l10n_configs/de.js'
import { mainConfig_el, defaultThemeConfig_el } from './l10n_configs/el.js'
import { mainConfig_en, defaultThemeConfig_en } from './l10n_configs/en.js'
import { mainConfig_es, defaultThemeConfig_es } from './l10n_configs/es.js'
import { mainConfig_fi, defaultThemeConfig_fi } from './l10n_configs/fi.js'
import { mainConfig_fr, defaultThemeConfig_fr } from './l10n_configs/fr.js'
import { mainConfig_he, defaultThemeConfig_he } from './l10n_configs/he.js'
import { mainConfig_hu, defaultThemeConfig_hu } from './l10n_configs/hu.js'
import { mainConfig_it, defaultThemeConfig_it } from './l10n_configs/it.js'
import { mainConfig_ja, defaultThemeConfig_ja } from './l10n_configs/ja.js'
import { mainConfig_ko, defaultThemeConfig_ko } from './l10n_configs/ko.js'
import { mainConfig_lv, defaultThemeConfig_lv } from './l10n_configs/lv.js'
import { mainConfig_nl, defaultThemeConfig_nl } from './l10n_configs/nl.js'
import { mainConfig_no, defaultThemeConfig_no } from './l10n_configs/no.js'
import { mainConfig_pl, defaultThemeConfig_pl } from './l10n_configs/pl.js'
import { mainConfig_pt_BR, defaultThemeConfig_pt_BR } from './l10n_configs/pt-BR.js'
import { mainConfig_pt, defaultThemeConfig_pt } from './l10n_configs/pt.js'
import { mainConfig_ro, defaultThemeConfig_ro } from './l10n_configs/ro.js'
import { mainConfig_ru, defaultThemeConfig_ru } from './l10n_configs/ru.js'
import { mainConfig_sr_Cyrl, defaultThemeConfig_sr_Cyrl } from './l10n_configs/sr-Cyrl.js'
import { mainConfig_sv, defaultThemeConfig_sv } from './l10n_configs/sv.js'
import { mainConfig_tr, defaultThemeConfig_tr } from './l10n_configs/tr.js'
import { mainConfig_uk, defaultThemeConfig_uk } from './l10n_configs/uk.js'
import { mainConfig_vi, defaultThemeConfig_vi } from './l10n_configs/vi.js'
import { mainConfig_zh_Hans, defaultThemeConfig_zh_Hans } from './l10n_configs/zh-Hans.js'
import { mainConfig_zh_Hant, defaultThemeConfig_zh_Hant } from './l10n_configs/zh-Hant.js'

export const mainConfig: SiteLocaleConfig = {
    '/l10n/af/': mainConfig_af,
    '/l10n/ar/': mainConfig_ar,
    '/l10n/ca/': mainConfig_ca,
    '/l10n/cs/': mainConfig_cs,
    '/l10n/da/': mainConfig_da,
    '/l10n/de/': mainConfig_de,
    '/l10n/el/': mainConfig_el,
    '/': mainConfig_en,
    '/l10n/es/': mainConfig_es,
    '/l10n/fi/': mainConfig_fi,
    '/l10n/fr/': mainConfig_fr,
    '/l10n/he/': mainConfig_he,
    '/l10n/hu/': mainConfig_hu,
    '/l10n/it/': mainConfig_it,
    '/l10n/ja/': mainConfig_ja,
    '/l10n/ko/': mainConfig_ko,
    '/l10n/lv/': mainConfig_lv,
    '/l10n/nl/': mainConfig_nl,
    '/l10n/no/': mainConfig_no,
    '/l10n/pl/': mainConfig_pl,
    '/l10n/pt-BR/': mainConfig_pt_BR,
    '/l10n/pt/': mainConfig_pt,
    '/l10n/ro/': mainConfig_ro,
    '/l10n/ru/': mainConfig_ru,
    '/l10n/sr-Cyrl/': mainConfig_sr_Cyrl,
    '/l10n/sv/': mainConfig_sv,
    '/l10n/tr/': mainConfig_tr,
    '/l10n/uk/': mainConfig_uk,
    '/l10n/vi/': mainConfig_vi,
    '/l10n/zh-Hans/': mainConfig_zh_Hans,
    '/l10n/zh-Hant/': mainConfig_zh_Hant,
}

export const defaultThemeConfig: LocaleConfig = {
    '/l10n/af/': defaultThemeConfig_af,
    '/l10n/ar/': defaultThemeConfig_ar,
    '/l10n/ca/': defaultThemeConfig_ca,
    '/l10n/cs/': defaultThemeConfig_cs,
    '/l10n/da/': defaultThemeConfig_da,
    '/l10n/de/': defaultThemeConfig_de,
    '/l10n/el/': defaultThemeConfig_el,
    '/': defaultThemeConfig_en,
    '/l10n/es/': defaultThemeConfig_es,
    '/l10n/fi/': defaultThemeConfig_fi,
    '/l10n/fr/': defaultThemeConfig_fr,
    '/l10n/he/': defaultThemeConfig_he,
    '/l10n/hu/': defaultThemeConfig_hu,
    '/l10n/it/': defaultThemeConfig_it,
    '/l10n/ja/': defaultThemeConfig_ja,
    '/l10n/ko/': defaultThemeConfig_ko,
    '/l10n/lv/': defaultThemeConfig_lv,
    '/l10n/nl/': defaultThemeConfig_nl,
    '/l10n/no/': defaultThemeConfig_no,
    '/l10n/pl/': defaultThemeConfig_pl,
    '/l10n/pt-BR/': defaultThemeConfig_pt_BR,
    '/l10n/pt/': defaultThemeConfig_pt,
    '/l10n/ro/': defaultThemeConfig_ro,
    '/l10n/ru/': defaultThemeConfig_ru,
    '/l10n/sr-Cyrl/': defaultThemeConfig_sr_Cyrl,
    '/l10n/sv/': defaultThemeConfig_sv,
    '/l10n/tr/': defaultThemeConfig_tr,
    '/l10n/uk/': defaultThemeConfig_uk,
    '/l10n/vi/': defaultThemeConfig_vi,
    '/l10n/zh-Hans/': defaultThemeConfig_zh_Hans,
    '/l10n/zh-Hant/': defaultThemeConfig_zh_Hant,
}
