/* This file is automatically generated by "gen_configs.py" */
import type { SiteLocaleConfig } from '@vuepress/shared'
import type { LocaleConfig } from '@vuepress/shared'

import { mainConfig_en, defaultThemeConfig_en } from './l10n_configs/en.js'
import { mainConfig_zh_Hans, defaultThemeConfig_zh_Hans } from './l10n_configs/zh-Hans.js'

export const mainConfig: SiteLocaleConfig = {
    '/': mainConfig_en,
    '/zh-Hans/': mainConfig_zh_Hans,
}

export const defaultThemeConfig: LocaleConfig = {
    '/': defaultThemeConfig_en,
    '/zh-Hans/': defaultThemeConfig_zh_Hans,
}
