//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AsciiArt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsciiArt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftClient.Resources.AsciiArt.AsciiArt", typeof(AsciiArt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║            Brewing Stand            ║
        ///║  ╔═══╗      ⡈ ⠄╔═══╗                ║
        ///║  ║ 4 ╟───╮  ⢠⡐⢈║ 3 ║ ┃              ║
        ///║  ╚═══╝ ╭─╯  ⠂⡠⢂╚╦╦╦╝ ┃              ║
        ///║        ╰───■■■■ ║║║  ▼              ║
        ///║           ╔═══╦═╝║╚═╦═══╗           ║
        ///║           ║ 0 ║╔═╩═╗║ 2 ║           ║
        ///║           ╚═══╝║ 1 ║╚═══╝           ║
        ///║ Inventory      ╚═══╝                ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 5 ║ 6 ║ 7 ║ 8 ║ 9 ║10 ║11 ║12 ║13 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_BrewingStand {
            get {
                return ResourceManager.GetString("Container.BrewingStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║        Crafting                     ║
        ///║       ╔═══╦═══╦═══╗                 ║
        ///║       ║ 1 ║ 2 ║ 3 ║                 ║
        ///║       ╠═══╬═══╬═══╣     ╔═══╗       ║
        ///║       ║ 4 ║ 5 ║ 6 ║ ━━▶ ║ 0 ║       ║
        ///║       ╠═══╬═══╬═══╣     ╚═══╝       ║
        ///║       ║ 7 ║ 8 ║ 9 ║                 ║
        ///║       ╚═══╩═══╩═══╝                 ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║18 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Crafting {
            get {
                return ResourceManager.GetString("Container.Crafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║   Enchant                           ║
        ///║             ╔════════════════════╗  ║
        ///║             ║         Top        ║  ║
        ///║  ╔═══╦═══╗  ╠════════════════════╣  ║
        ///║  ║ 0 ║ 1 ║  ║        Middle      ║  ║
        ///║  ╚═══╩═══╝  ╠════════════════════╣  ║
        ///║             ║        Bottom      ║  ║
        ///║             ╚════════════════════╝  ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 2 ║ 3 ║ 4 ║ 5 ║ 6 ║ 7 ║ 8 ║ 9 ║10 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_EnchantingTable {
            get {
                return ResourceManager.GetString("Container.EnchantingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║              Container              ║
        ///║           ╔═══╗                     ║
        ///║           ║ 0 ║                     ║
        ///║           ╚═══╝      ╔═══╗          ║
        ///║            ⠂⡠⢂   ━━▶ ║ 2 ║          ║
        ///║            ⠂⡠⢂       ╚═══╝          ║
        ///║           ╔═══╗                     ║
        ///║           ║ 1 ║                     ║
        ///║           ╚═══╝                     ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 3 ║ 4 ║ 5 ║ 6 ║ 7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Furnace {
            get {
                return ResourceManager.GetString("Container.Furnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║             Container               ║
        ///║            ╔═══╦═══╦═══╗            ║
        ///║            ║ 0 ║ 1 ║ 2 ║            ║
        ///║            ╠═══╬═══╬═══╣            ║
        ///║            ║ 3 ║ 4 ║ 5 ║            ║
        ///║            ╠═══╬═══╬═══╣            ║
        ///║            ║ 6 ║ 7 ║ 8 ║            ║
        ///║            ╚═══╩═══╩═══╝            ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Generic_3x3 {
            get {
                return ResourceManager.GetString("Container.Generic_3x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║ Container                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 0 ║ 1 ║ 2 ║ 3 ║ 4 ║ 5 ║ 6 ║ 7 ║ 8 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║18 ║19 ║20 ║21 ║22 ║23 ║24 ║25 ║26 ║║
        ///║╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║27 ║28 ║29 ║30 ║31 ║32 ║33 ║34 ║35 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Generic_9x3 {
            get {
                return ResourceManager.GetString("Container.Generic_9x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║ Container                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 0 ║ 1 ║ 2 ║ 3 ║ 4 ║ 5 ║ 6 ║ 7 ║ 8 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║18 ║19 ║20 ║21 ║22 ║23 ║24 ║25 ║26 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║27 ║28 ║29 ║30 ║31 ║32 ║33 ║34 ║35 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║36 ║37 ║38 ║39 ║40 ║41 ║42 ║43 ║44 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Generic_9x6 {
            get {
                return ResourceManager.GetString("Container.Generic_9x6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║ Repair &amp; Disenchant                 ║
        ///║     ╔═════════╗                     ║
        ///║     ║  ╔═══╗  ║                     ║
        ///║  ╔══║  ║ 0 ║  ║══╗                  ║
        ///║  ║  ║  ╚═══╝  ║  ║                  ║
        ///║  ║  ║  ╔═══╗  ║  ║       ╔═══╗      ║
        ///║  ║  ║  ║ 1 ║  ║  ║  ━━▶  ║ 2 ║      ║
        ///║  ║  ║  ╚═══╝  ║  ║       ╚═══╝      ║
        ///║  ║  ╠═════════╣  ║                  ║
        ///║  ║  ║         ║  ║                  ║
        ///║  ╚══╝         ╚══╝                  ║
        ///║                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Grindstone {
            get {
                return ResourceManager.GetString("Container.Grindstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║ Container                           ║
        ///║        ╔═══╦═══╦═══╦═══╦═══╗        ║
        ///║        ║ 0 ║ 1 ║ 2 ║ 3 ║ 4 ║        ║
        ///║        ╚═══╩═══╩═══╩═══╩═══╝        ║
        ///║ Inventory                           ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 5 ║ 6 ║ 7 ║ 8 ║ 9 ║10 ║11 ║12 ║13 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║14 ║15 ║16 ║17 ║18 ║19 ║20 ║21 ║22 ║║
        ///║╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣║
        ///║║23 ║24 ║25 ║26 ║27 ║28 ║29 ║30 ║31 ║║
        ///║╚═══╩═══╩═══╩═══╩══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_Hopper {
            get {
                return ResourceManager.GetString("Container.Hopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════════════════════════════╗
        ///║╔═══╦═══════════╗                    ║
        ///║║ 5 ║    ███    ║   ╔═══╦═══╗        ║
        ///║╠═══╣    ███    ║   ║ 1 ║ 2 ║   ╔═══╗║
        ///║║ 6 ║  ███████  ║   ╠═══╬═══╣━━▶║ 0 ║║
        ///║╠═══╣  ███████  ║   ║ 3 ║ 4 ║   ╚═══╝║
        ///║║ 7 ║  ███████  ║   ╚═══╩═══╝        ║
        ///║╠═══╣    ███    ╠═══╗                ║
        ///║║ 8 ║    ███    ║45 ║                ║
        ///║╚═══╩═══════════╩═══╝                ║
        ///║╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗║
        ///║║ 9 ║10 ║11 ║12 ║13 ║14 ║15 ║16 ║17 ║║
        ///║╠═══╬═══╬═══╬═══╬══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Container_PlayerInventory {
            get {
                return ResourceManager.GetString("Container_PlayerInventory", resourceCulture);
            }
        }
    }
}
