/* This file is automatically generated by "gen_configs.py" */
import type { SiteLocaleData  } from '@vuepress/shared'
import type { DefaultThemeLocaleData } from '@vuepress/theme-default'
import { headConfig } from '../head.js'

const Translation = require('../../translations/uk.json')

export const mainConfig_uk: SiteLocaleData  = {
    lang: 'uk',
    title: Translation.title,
    description: Translation.description,
    head: headConfig
}

export const defaultThemeConfig_uk: DefaultThemeLocaleData = {
    selectLanguageName: "Українська",
    selectLanguageText: Translation.theme.selectLanguageText,
    selectLanguageAriaLabel: Translation.theme.selectLanguageAriaLabel,

    navbar: [
        {
            text: Translation.navbar.AboutAndFeatures,
            link: "/uk/guide/",
        },
        
        {
            text: Translation.navbar.Installation,
            link: "/uk/guide/installation.md",
        },
      
        {
            text: Translation.navbar.Usage,
            link: "/uk/guide/usage.md",
        },
      
        {
            text: Translation.navbar.Configuration,
            link: "/uk/guide/configuration.md",
        },
      
        {
            text: Translation.navbar.ChatBots,
            link: "/uk/guide/chat-bots.md",
        },
    ],

    sidebar: [
        "/uk/guide/README.md", 
        "/uk/guide/installation.md", 
        "/uk/guide/usage.md", 
        "/uk/guide/configuration.md", 
        "/uk/guide/chat-bots.md", 
        "/uk/guide/creating-bots.md", 
        "/uk/guide/contibuting.md"
    ],

    // page meta
    editLinkText: Translation.theme.editLinkText,
    lastUpdatedText: Translation.theme.lastUpdatedText,
    contributorsText: Translation.theme.contributorsText,

    // custom containers
    tip: Translation.theme.tip,
    warning: Translation.theme.warning,
    danger: Translation.theme.danger,

    // 404 page
    notFound: Translation.theme.notFound,
    backToHome: Translation.theme.backToHome,

    // a11y
    openInNewWindow: Translation.theme.openInNewWindow,
    toggleColorMode: Translation.theme.toggleColorMode,
    toggleSidebar: Translation.theme.toggleSidebar,
}
